# coding: utf-8

"""
    API de gestion des messages entre utilisateurs

    Api Messages  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sylouan.corfa@epsi.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.msg_api import MsgApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMsgApi(unittest.TestCase):
    """MsgApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.msg_api.MsgApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_receive(self):
        """Test case for receive

        Reçoit les messages venant d'un utilisateur  # noqa: E501
        """
        pass

    def test_send(self):
        """Test case for send

        Envoie un message à un receveur  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
