# Generated by Django 3.0 on 2019-12-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 15, 18, 2, 432417)),
        ),
    ]
