# Generated by Django 3.0 on 2020-01-08 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_msg', '0002_message_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 9, 53, 2, 775203)),
        ),
    ]
