# Generated by Django 3.0 on 2020-01-08 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_msg', '0003_auto_20200108_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 10, 4, 39, 542983)),
        ),
    ]
