# coding: utf-8

# flake8: noqa

"""
    API de gestion des messages entre utilisateurs

    Api Messages  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sylouan.corfa@epsi.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.msg_api import MsgApi
from swagger_client.api.users_api import UsersApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
