# Generated by Django 3.0 on 2020-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_groups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=30)),
                ('prenom', models.TextField(max_length=30)),
                ('username', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=512, null=True)),
                ('groups', models.ManyToManyField(to='api_groups.Group')),
            ],
        ),
    ]
