# Generated by Django 3.0 on 2019-12-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0007_auto_20191203_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
