# Generated by Django 3.0 on 2019-12-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
