# Generated by Django 3.0 on 2020-01-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_groups', '__first__'),
        ('api_users', '0010_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='api_groups.Group'),
        ),
    ]
